# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_TDD_Learning' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS_TDD_Learning

  pod 'Typhoon'
  pod 'SnapKit', '~> 4.0.0'

  target 'IOS_TDD_LearningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS_TDD_LearningUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
